services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: api-minhas-despesas
        ports:
            - "3000:3000"
        restart: always
        env_file:
            - .env
        depends_on:
            - localstack
            - postgres

    postgres:
        image: postgres:15
        container_name: postgres-minhas-despesas
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres

    localstack:
        image: localstack/localstack:latest
        container_name: localstack-minhas-despesas
        ports:
            - "4566:4566"
            - 4571:4571
        environment:
            SERVICES: "s3,sqs"
            DEBUG: "1"
        volumes:
            - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/localstack-init.sh
